// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SPMS.Data;

namespace SPMS.Migrations.InitialCreate
{
 [DbContext(typeof(AppDbContext))]
 [Migration("20260424_InitialCreate")]
 partial class InitialCreate
 {
 }
}